SignalATM.Web/Models/Ticket.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalATM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketResponses = new HashSet<TicketRespons>();
        }
    
        public int TicketsID { get; set; }
        public int FromID { get; set; }
        public int ToID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public int TicketStatusID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public bool Screen { get; set; }
    
        public virtual mstTicketStatu mstTicketStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketRespons> TicketResponses { get; set; }
    }
}

SignalATM.Web/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalATM.Web.Controllers
{
    public class DocumentsController : Controller
    {
        // GET: Documents
        public ActionResult Index()
        {
            return View();
        }
    }
}

SignalATM.Web/Controllers/PersonalDetailsController.cs
using CsQuery.ExtensionMethods.Internal;
using SignalATM.Commons;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalATM.Web.Controllers
{
    public class PersonalDetailsController : Controller
    {
        // GET: PersonalDetails
        public GlobalVariables globalVariables = new GlobalVariables();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetCountry()
        {            
            try
            {             
                var dataTableResult = SqlCommons.ExecuteStoreProcedure(globalVariables.SignalATMDbConn, StoredProcedures.GetCountry);
                return Json(new { success = false, result = dataTableResult }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                Debug.logError(string.Format("Exception occured in Home.VerifyOTPToRegister. Ex:- {0}", ex.Message));
                return Json(new { success = false, result = "fail" }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult GetAllStateByCountryID(int countryID)
        {           
            try
            {
                Hashtable hInput = new Hashtable();
                hInput.Add("@CountryID", countryID);
                DataTable queryResult = SqlCommons.ExecuteStoreProcedure(globalVariables.SignalATMDbConn, StoredProcedures.GetAllStateByCountryID, hInput);

                return Json(new { success = false, result = queryResult }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                Debug.logError(string.Format("Exception occured in Home.VerifyOTPToRegister. Ex:- {0}", ex.Message));
                return Json(new { success = false, result = "fail" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

SignalATM.Web/Controllers/ReferrerController.cs
using InfoFreightSystem;
using Newtonsoft.Json;
//using Razorpay.Api;
using SignalATM.Commons;
using SignalATM.Web.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SignalATM.Web.Controllers
{
    public class ReferrerController : Controller
    {

        SQLDataAccess sqlDataAccess;
        Hashtable inputParams;
        public GlobalVariables globalVariables;
        public static string orderId;
        public ActionResult Index()
        {
            return View();
        }
        public ReferrerController()
        {
            try
            {
               // string emailId = "deepti.10m@gmail.com";
                string emailId=System.Web.HttpContext.Current.Session["UserId"].ToString();                            
                sqlDataAccess = new SQLDataAccess();
            //    globalVariables = new GlobalVariables(emailId);
                ViewData["WalletAmount"] = globalVariables.UserWalletBalance;
            }
            catch (Exception ex)
            {

            }
        }
        #region ReferrerProfile
        public ActionResult PersonalDetails()
        {
            ViewBag.UserEmail = Session["UserId"].ToString();
            ViewBag.userID = globalVariables.SecUserID;
            return View();
        }
        public string GetPersonalDetails()
        {
            string str = "";
            inputParams = new Hashtable();
            inputParams.Add("@UserID", globalVariables.SecUserID);
            sqlDataAccess = new SQLDataAccess();
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetPersonalDetails", inputParams);
            if (dt.Rows.Count == 0)
            {
                str = "0";
            }
            else
            {
                str = JsonConvert.SerializeObject(dt);
            }
            return str;
        }
        public ActionResult GetPersonalDetailsForGlobalProfile()
        {
            string str = "";
            try
            {

                inputParams = new Hashtable();
                inputParams.Add("@UserID", globalVariables.SecUserID);
                sqlDataAccess = new SQLDataAccess();
                String[] DocArray = new String[6];
                var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetPersonalDetails", inputParams);

                if (dt.Rows.Count == 0)
                {
                    str = "0";
                }
                else
                {
                    DocArray[0] = dt.Rows[0]["UserName"].ToString();
                    DocArray[1] = dt.Rows[0]["AboutMe"].ToString();
                    DocArray[2] = dt.Rows[0]["Email"].ToString();
                    DocArray[3] = dt.Rows[0]["EntryDate"].ToString();
                    DocArray[4] = dt.Rows[0]["ApplicationUserPhoneNumber"].ToString();
                    DocArray[5] = Encoding.ASCII.GetString((byte[])dt.Rows[0]["UserImage"]);
                }

                return Json(new { success = true, response = DocArray }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = true, response = str }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public ActionResult SubmitPersonalDetails(string result)
        {
            try
            {
                var fileName = "";
                var path = "";
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    fileName = Path.GetFileName(file.FileName);
                    path = Path.Combine(Server.MapPath("~/Content/CSS/img"), fileName);
                    file.SaveAs(path);
                }
                byte[] theBytes = Encoding.UTF8.GetBytes(fileName);
                dynamic obj = JsonConvert.DeserializeObject(result);
                inputParams = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                inputParams.Add("@iUserID", globalVariables.SecUserID);
                inputParams.Add("@strUserName", obj.Name.ToString());
                inputParams.Add("@strDisplayName", obj.DisplayName.ToString());
                inputParams.Add("@strEmail", obj.Email.ToString());
                inputParams.Add("@strUserPhoneNO", obj.Phone.ToString());
                inputParams.Add("@iGender", obj.Gender.ToString());
                inputParams.Add("@strUserAddress", obj.Address.ToString());
                inputParams.Add("@iCountryID", obj.Country.ToString());
                inputParams.Add("@iTimeZone", obj.TimeZone.ToString());
                inputParams.Add("@strState", obj.State.ToString());
                inputParams.Add("@strCity", obj.City.ToString());
                inputParams.Add("@strAboutMe", obj.Aboutme.ToString());
                inputParams.Add("@iUserReferenceID", globalVariables.SecApplicationUserID);
                inputParams.Add("@strUserUrl", obj.Website.ToString());
                inputParams.Add("@bUserImage", theBytes);
                string resp = sqlDataAccess.ExecuteStoreProcedure("usp_SavePersonalDetails", inputParams);
                return Json(new { success = true, response = resp }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return Json(new { success = true, response = msg }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public ActionResult EditPersonalDetails(string result)
        {
            try
            {
                var fileName = "";
                var path = "";
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    fileName = Path.GetFileName(file.FileName);
                    path = Path.Combine(Server.MapPath("~/Content/CSS/img"), fileName);
                    file.SaveAs(path);
                }
                byte[] theBytes = Encoding.UTF8.GetBytes(fileName);
                dynamic obj = JsonConvert.DeserializeObject(result);
                inputParams = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                inputParams.Add("@iUserID", globalVariables.SecUserID);
                inputParams.Add("@strUserName", obj.Name.ToString());
                inputParams.Add("@strDisplayName", obj.DisplayName.ToString());
                inputParams.Add("@strEmail", obj.Email.ToString());
                inputParams.Add("@strUserPhoneNO", obj.Phone.ToString());
                inputParams.Add("@iGender", obj.Gender.ToString());
                inputParams.Add("@strUserAddress", obj.Address.ToString());
                inputParams.Add("@iCountryID", obj.Country.ToString());
                inputParams.Add("@iTimeZone", obj.TimeZone.ToString());
                inputParams.Add("@strState", obj.State.ToString());
                inputParams.Add("@strCity", obj.City.ToString());
                inputParams.Add("@strAboutMe", obj.Aboutme.ToString());
                inputParams.Add("@iUserReferenceID", globalVariables.SecApplicationUserID);
                inputParams.Add("@strUserUrl", obj.Website.ToString());
                inputParams.Add("@bUserImage", theBytes);
                string resp = sqlDataAccess.ExecuteStoreProcedure("usp_UpdatePersonalDetails", inputParams);
                return Json(new { success = true, response = resp }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return Json(new { success = true, response = msg }, JsonRequestBehavior.AllowGet);
            }
        }
        public string GetContryCityStateGender()
        {
            inputParams = new Hashtable();
            inputParams.Add("@", globalVariables.SecUserID);
            sqlDataAccess = new SQLDataAccess();
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetCountry");
            var dt1 = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetAllStateByCountryID", inputParams);
            var dt2 = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetAllCityByStateID", inputParams);
            string str = JsonConvert.SerializeObject(dt);
            return str;
        }
        public ActionResult GetCountries()
        {
            List<mstCountry> countryList = new List<mstCountry>();
            sqlDataAccess = new SQLDataAccess();
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetCountry");
            foreach (DataRow r in dt.Rows)
            {
                countryList.Add(new mstCountry
                {
                    CountryID = Convert.ToInt32(r["CountryID"]),
                    Country = r["Country"].ToString()
                });
            }
            return Json(new { success = true, CountryList = countryList }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetStates(int countryID)
        {
            List<mstState> stateList = new List<mstState>();
            sqlDataAccess = new SQLDataAccess();
            inputParams = new Hashtable();
            inputParams.Add("@iCountryID", countryID);
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetAllStateByCountryID", inputParams);
            foreach (DataRow r in dt.Rows)
            {
                stateList.Add(new mstState
                {
                    StateID = Convert.ToInt32(r["StateID"]),
                    StateName = r["StateName"].ToString()
                });
            }

SignalATM.Web/Views/Referrer/Cashouts.cshtml
@{
    ViewBag.Title = "Cashouts";
    Layout = "~/Views/Shared/_Ref_master_page.cshtml";
}
<section class="content" ng-app="app" ng-controller="mycontrol">
    <form name="createSignal">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title yellowtitle">
                            <div class="col-md-7 pad0">
                                <button class="btn btn-xs btn-warning collapse-link" type="submit"><i class="fa fa-plus" aria-hidden="true"></i> New Cashout Request</button>
                            </div>
                        </div>
                        <div class="ibox-content" style="display:none;">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-4 pad0">
                                        <div class="form-group">
                                            <label>Current Wallet Amount</label>
                                            <input name="" type="text" class="input-control" id="txtWalletAmount" readonly="">
                                        </div>
                                        <div class="form-group">
                                            <label>Request Cashout Amount (Enter Value)</label>
                                            <input type="number" class="input-control" id="txtCashoutAmount" ng-model="txtCashoutAmount" onchange="CalculationAmount()">
                                            <label for="error" n id="incorrectDetails" style="margin:10px auto 6px auto;color:Red; line-height:11px;font-size:small; display:none"> </label>

                                        </div>
                                        <div class="form-group">
                                            <label>Balance Wallet Amount</label>
                                            <input type="number" class="input-control" readonly="" id="txtBalanceAmount" ng-model="txtBalanceAmount">
                                        </div>
                                        <hr>
                                        <div class="col-md-12 pad0">
                                            <button class="btn btn-sm btn-primary" type="submit" ng-click="SubmitCashout()">Submit</button>
                                        </div>
                                        <div style="clear:both;"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title redtitle">
                            <h5>Cashout</h5>
                            <div class="ibox-tools"> <a class="collapse-link"> <i class="fa fa-chevron-down"></i> </a> <a class="close-link"> <i class="fa fa-times"></i> </a> </div>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-md-11">
                                    <div class="row">
                                        <div class="search-d">
                                            <div class="input-group">
                                                <input type="text" class="searchi">
                                                <div class="input-group-append">
                                                    <button class="btn btn-primary btn-xs" type="button">
                                                        Submit
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table width="100%" class="table table-striped table-bordered" id="example2">
                                            <thead>
                                                <tr>
                                                    <th width="45">ID</th>
                                                    @*<th width="72">Voucher</th>*@
                                                    <th width="101">Submitted</th>
                                                    <th width="86">Amount </th>
                                                    <th width="93">Balance</th>
                                                    <th width="93">Status </th>
                                                    <th width="87">Source</th>
                                                    <th width="147">Transaction</th>
                                                    <th width="183">Comments</th>
                                                    <th width="183">Completed</th>
                                                </tr>
                                            </thead>
                                            <tbody id="CashoutDetails">
                                                @*<tr>
                                                        <td>01</td>
                                                        <td><a href="../trader/tr-invoice.pdf" target="_blank">CO01</a></td>
                                                        <td>
                                                            9:30am <br>
                                                            15-Dec-19
                                                        </td>
                                                        <td>$50</td>
                                                        <td>$50</td>
                                                        <td>Pending</td>
                                                        <td>Wallet</td>
                                                        <td>#C0001256</td>
                                                        <td>
                                                            Lorem ipsum<br>
                                                            <a href="#">Read more</a>
                                                        </td>
                                                        <td>10:30am <br>16-Dec-19</td>
                                                    </tr>*@
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
<script src="http://ajax.microsoft.com/ajax/jquery/jquery-1.10.2.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.2/angular.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery/1.12.4/jquery.min.js"></script>
<script>
            var app = angular.module('app', []);
            app.controller('mycontrol', function ($scope, $http, $location) {
                GetData();
                GetWalletAmount();
                $scope.SubmitCashout = function () {
                    var RequestAmout = $scope.txtCashoutAmount;
                    var CurrentWallentAmount = $('#txtBalanceAmount').val();
                    $.ajax({
                        url:'@Url.Action("AddCashoutAmountDeatils", "Referrer")',
                        type:"POST",
                        Response:ContentType = 'application/json',
                        data: { RequestAmout: RequestAmout, CurrentWallentAmount:CurrentWallentAmount },
                        success: function () {
                            //alert("Insert  data successfully");
                            location.reload();
                        }
                    });
                }

                function GetWalletAmount()
                {
                    //alert("test");
                    $.ajax({
                        url:'@Url.Action("GetWalletAmountByID", "Referrer")',
                        type:"GET",
                        Response:ContentType = 'application/json',
                        data:{},
                        success: function (data) {
                           // alert(data);
                            $('#txtWalletAmount').val(data);
                        }
                    });

                }
                function GetData() {
                    $.ajax({
                        url: '@Url.Action("GetCashout", "Referrer")',
                        type: "GET",
                        Response: ContentType = 'application/json',
                        data: {},
                        success: function (data) {
                            var str = JSON.parse(data);
                            var htmlStr = "";
                            for (var i = 0; i < str.length; i++) {
                                htmlStr += '<tr id="riskRow">';
                                htmlStr += '<td id="row">' + str[i].RequestID + '</td>';
                                var entryDate = GetTwoDigitDateFormat(str[i].EntryDate);
                                htmlStr += '<td>' + entryDate + '</td>';
                                htmlStr += '<td>' + str[i].RequestAmount + '</td>';
                                htmlStr += '<td>' + str[i].CurrentWalletBalance + '</td>';
                                htmlStr += '<td>' + str[i].PaymentStatus + '</td>';
                                htmlStr += '<td>' + str[i].Name + '</td>';
                                htmlStr += '<td>' + str[i].TransactionDetails + '</td>';
                               // htmlStr += '<td>' + str[i].Comments + '</td>';
                                htmlStr += '<td>' + str[i].Comments + '</td>';// <div class="more"> <p class="m-0">  </p> </div>
                                var requestCompletedOn = GetTwoDigitDateFormat(str[i].RequestCompletedOn);
                                htmlStr += '<td>' + requestCompletedOn + '</td>';
                                //htmlStr += ' <td><button type="button"  onclick="Edit(' + '' + str[i].RiskID + '' + ',' + '\'' + str[i].RiskName + '\'' + ',' + '\'' + str[i].Status + '\'' + ',' + '\'' + str[i].EntryDate + '\'' + ')"> <i class="fa fa-edit" aria-hidden="true" title="Edit"></i></button></td>';
                                //htmlStr += ' <td><a href="admin-as-signal-type.html#details"><i class="fa fa-eye" aria-hidden="true" title="View"></i></a></td>';
                                //htmlStr += ' <td><button type="button" class="btn btn-danger btn-xs" onclick="Delete(' + str[i].RiskID + ')"> <i class="fa fa-remove"></i>&nbsp;Remove</button></td>';
                                htmlStr += '</tr>';
                            }
                            $("#CashoutDetails").html(htmlStr)
                        }
                    });
                }




            });
   function CalculationAmount()
   {
       var TotalAmount = parseInt($("#txtWalletAmount").val());
       var CashoutAmount = parseInt($("#txtCashoutAmount").val());
      // Document.getElementById("#txtBalanceAmount").reset();
       if (TotalAmount >= CashoutAmount)
       {
           $("#incorrectDetails").hide();
           var Result = (TotalAmount - CashoutAmount);
           $('#txtBalanceAmount').val(Result);
           //alert(Result);
       }
       else
       {
           $("#incorrectDetails").show();
           $("#txtBalanceAmount").empty();
           $("#incorrectDetails").html("Requested Amount is Greater Than Wallet Balance Amount !");
           $('#txtBalanceAmount').val(0);
           //$("#txtCashoutAmount").val(0)
       }


    }
</script>

SignalATM.Web/Views/Referrer/Earnings.cshtml
@{
    ViewBag.Title = "Earnings";
    Layout = "~/Views/Shared/_Ref_master_page.cshtml";
}

<div class="wrapper wrapper-content">
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12 pad0">
            <div class="ibox">
                <div class="ibox-title yellowtitle">
                    <h5>Earnings</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="search-d">
                            <div class="input-group">
                                <input type="text" class="searchi">
                                <div class="input-group-append">
                                    <button class="btn btn-primary btn-xs" type="button">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 pad0">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered" id="example1">

                                <thead>
                                    <tr>
                                        <th width="41">ID</th>
                                        <th width="77">Period</th>
                                        <th width="96">From </th>
                                        <th width="114">To</th>
                                        <th width="204">Referrer Name</th>
                                        <th width="163">Trader Name </th>
                                        <th width="98">Transaction </th>

                                        <th width="85" title="Past">Earnings</th>
                                        <th width="227" title="Past">Entry Date</th>
                                        <th width="78" title="Past">Status</th>
                                        <th width="99" title="Past">Type</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>#1</td>
                                        <td>Period 1	</td>
                                        <td>01-Dec-19	</td>
                                        <td> 15-Dec-19	</td>
                                        <td>Mahesh Kulkarni</td>
                                        <td>mahk@gmail.com</td>
                                        <td>$150</td>
                                        <td>$70</td>
                                        <td>6.30 am, 12-Dec-19</td>
                                        <td>Pending</td>
                                        <td>-</td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
    </div>

SignalATM.Web/Views/Referrer/SiteMap.cshtml
@{
    ViewBag.Title = "SiteMap";
    Layout = "~/Views/Shared/_Ref_master_page.cshtml";
}

<h2>SiteMap</h2>