SignalATM.Web/Models/Ticket.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalATM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketResponses = new HashSet<TicketRespons>();
        }
    
        public int TicketsID { get; set; }
        public int FromID { get; set; }
        public int ToID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public int TicketStatusID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public bool Screen { get; set; }
    
        public virtual mstTicketStatu mstTicketStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketRespons> TicketResponses { get; set; }
    }
}

SignalATM.Web/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalATM.Web.Controllers
{
    public class DocumentsController : Controller
    {
        // GET: Documents
        public ActionResult Index()
        {
            return View();
        }
    }
}

SignalATM.Web/Controllers/PersonalDetailsController.cs
using CsQuery.ExtensionMethods.Internal;
using SignalATM.Commons;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalATM.Web.Controllers
{
    public class PersonalDetailsController : Controller
    {
        // GET: PersonalDetails
        public GlobalVariables globalVariables = new GlobalVariables();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetCountry()
        {            
            try
            {             
                var dataTableResult = SqlCommons.ExecuteStoreProcedure(globalVariables.SignalATMDbConn, StoredProcedures.GetCountry);
                return Json(new { success = false, result = dataTableResult }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                Debug.logError(string.Format("Exception occured in Home.VerifyOTPToRegister. Ex:- {0}", ex.Message));
                return Json(new { success = false, result = "fail" }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult GetAllStateByCountryID(int countryID)
        {           
            try
            {
                Hashtable hInput = new Hashtable();
                hInput.Add("@CountryID", countryID);
                DataTable queryResult = SqlCommons.ExecuteStoreProcedure(globalVariables.SignalATMDbConn, StoredProcedures.GetAllStateByCountryID, hInput);

                return Json(new { success = false, result = queryResult }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                Debug.logError(string.Format("Exception occured in Home.VerifyOTPToRegister. Ex:- {0}", ex.Message));
                return Json(new { success = false, result = "fail" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

SignalATM.Web/Controllers/TraderController.cs
using InfoFreightSystem;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
//using Razorpay.Api;
using SignalATM.Commons;
using SignalATM.Web.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SignalATM.Web.Controllers
{
    public class TraderController : Controller
    {
        // GET: Trader
        SQLDataAccess sqlDataAccess;
        Hashtable inputParams;
        public GlobalVariables globalVariables;
        public static string orderId;
        public TraderController()
        {
            string emailId =System.Web.HttpContext.Current.Session["UserId"].ToString();
            if (emailId != "")
            {
                sqlDataAccess = new SQLDataAccess();
               // globalVariables = new GlobalVariables(emailId);
                ViewData["WalletAmount"] = globalVariables.UserWalletBalance;
            }
        }
        public JsonResult Getmarkets()
        {
            List<mstMarket> MarketList = new List<mstMarket>();
            sqlDataAccess = new SQLDataAccess();
            inputParams = new Hashtable();
            inputParams.Add("@iUserID", globalVariables.SecUserID);
            var result = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetMarketsForGlobalVariables", inputParams);
            foreach (DataRow dr in result.Rows)
            {
                MarketList.Add(new mstMarket
                {
                    MarketID = Convert.ToInt32(dr["MarketID"]),
                    MarketName = dr["MarketName"].ToString()
                });
            }

            return Json(MarketList, JsonRequestBehavior.AllowGet);
        }
        public void SetGlobalMarket(int marketId)
        {
            globalVariables.MarketID = marketId;
        }
        public ActionResult Index()
        {
            return View();
        }
        #region Profile
        public ActionResult PersonalDetails()
        {
            ViewBag.UserEmail = Session["UserId"].ToString();
            ViewBag.userID = globalVariables.SecUserID;
            return View();
        }
        public string GetPersonalDetails()
        {
            string str = "";
            inputParams = new Hashtable();
            inputParams.Add("@UserID", globalVariables.SecUserID);
            sqlDataAccess = new SQLDataAccess();
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetPersonalDetails", inputParams);
            if (dt.Rows.Count == 0)
            {
                str = "0";
            }
            else
            {
                string pic = Encoding.ASCII.GetString((byte[])dt.Rows[0]["UserImage"]);
                ViewBag.UserImage = pic;
                str = JsonConvert.SerializeObject(dt);
            }
            return str;
        }
        public ActionResult GetPersonalDetailsForGlobalProfile()
        {
            string str = "";
            try
            {

                inputParams = new Hashtable();
                inputParams.Add("@UserID", globalVariables.SecUserID);
                sqlDataAccess = new SQLDataAccess();
                String[] DocArray = new String[6];
                var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetPersonalDetails", inputParams);

                if (dt.Rows.Count == 0)
                {
                    str = "0";
                }
                else
                {
                    DocArray[0] = dt.Rows[0]["UserName"].ToString();
                    DocArray[1] = dt.Rows[0]["AboutMe"].ToString();
                    DocArray[2] = dt.Rows[0]["Email"].ToString();
                    DocArray[3] = dt.Rows[0]["EntryDate"].ToString();
                    DocArray[4] = dt.Rows[0]["ApplicationUserPhoneNumber"].ToString();
                    DocArray[5] = Encoding.ASCII.GetString((byte[])dt.Rows[0]["UserImage"]);
                }

                return Json(new { success = true, response = DocArray }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = true, response = str }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public ActionResult SubmitPersonalDetails(string result)
        {
            try
            {
                var fileName = "";
                var path = "";
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    fileName = Path.GetFileName(file.FileName);
                    path = Path.Combine(Server.MapPath("~/Content/CSS/img"), fileName);
                    file.SaveAs(path);
                }
                byte[] theBytes = Encoding.UTF8.GetBytes(fileName);
                dynamic obj = JsonConvert.DeserializeObject(result);
                inputParams = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                inputParams.Add("@iUserID", globalVariables.SecUserID);
                inputParams.Add("@strUserName", obj.Name.ToString());
                inputParams.Add("@strDisplayName", obj.DisplayName.ToString());
                inputParams.Add("@strEmail", obj.Email.ToString());
                inputParams.Add("@strUserPhoneNO", obj.Phone.ToString());
                inputParams.Add("@iGender", obj.Gender.ToString());
                inputParams.Add("@strUserAddress", obj.Address.ToString());
                inputParams.Add("@iCountryID", obj.Country.ToString());
                inputParams.Add("@iTimeZone", obj.TimeZone.ToString());
                inputParams.Add("@strState", obj.State.ToString());
                inputParams.Add("@strCity", obj.City.ToString());
                inputParams.Add("@strAboutMe", obj.Aboutme.ToString());
                inputParams.Add("@iUserReferenceID", globalVariables.SecApplicationUserID);
                inputParams.Add("@strUserUrl", obj.Website.ToString());
                inputParams.Add("@bUserImage", theBytes);
                string resp = sqlDataAccess.ExecuteStoreProcedure("usp_SavePersonalDetails", inputParams);
                return Json(new { success = true, response = resp }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return Json(new { success = true, response = msg }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public ActionResult EditPersonalDetails(string result)
        {
            try
            {
                var fileName = "";
                var path = "";
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    fileName = Path.GetFileName(file.FileName);
                    path = Path.Combine(Server.MapPath("../Content/CSS/img"), fileName);
                    file.SaveAs(path);
                }
                byte[] theBytes = Encoding.UTF8.GetBytes(fileName);
                dynamic obj = JsonConvert.DeserializeObject(result);
                inputParams = new Hashtable();
                sqlDataAccess = new SQLDataAccess();
                inputParams.Add("@iUserID", globalVariables.SecUserID);
                inputParams.Add("@strUserName", obj.Name.ToString());
                inputParams.Add("@strDisplayName", obj.DisplayName.ToString());
                inputParams.Add("@strEmail", obj.Email.ToString());
                inputParams.Add("@strUserPhoneNO", obj.Phone.ToString());
                inputParams.Add("@iGender", obj.Gender.ToString());
                inputParams.Add("@strUserAddress", obj.Address.ToString());
                inputParams.Add("@iCountryID", obj.Country.ToString());
                inputParams.Add("@iTimeZone", obj.TimeZone.ToString());
                inputParams.Add("@strState", obj.State.ToString());
                inputParams.Add("@strCity", obj.City.ToString());
                inputParams.Add("@strAboutMe", obj.AboutMe.ToString());
                inputParams.Add("@iUserReferenceID", globalVariables.SecApplicationUserID);
                inputParams.Add("@strUserUrl", obj.Website.ToString());
                inputParams.Add("@bUserImage", theBytes);
                string resp = sqlDataAccess.ExecuteStoreProcedure("usp_UpdatePersonalDetails", inputParams);
                return Json(new { success = true, response = resp }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return Json(new { success = true, response = msg }, JsonRequestBehavior.AllowGet);
            }
        }
        public string GetContryCityStateGender()
        {
            inputParams = new Hashtable();
            inputParams.Add("@", globalVariables.SecUserID);
            sqlDataAccess = new SQLDataAccess();
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetCountry");
            var dt1 = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetAllStateByCountryID", inputParams);
            var dt2 = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetAllCityByStateID", inputParams);
            string str = JsonConvert.SerializeObject(dt);
            return str;
        }
        public ActionResult GetCountries()
        {
            List<mstCountry> countryList = new List<mstCountry>();
            sqlDataAccess = new SQLDataAccess();
            var dt = sqlDataAccess.GetDatatableExecuteStoreProcedure("usp_GetCountry");
            foreach (DataRow r in dt.Rows)
            {
                countryList.Add(new mstCountry
                {

SignalATM.Web/Views/Trader/Feedback.cshtml
@{
    ViewBag.Title = "Feedback";
    Layout = "~/Views/Shared/tr_master_page.cshtml";
}
<section class="content" ng-app="app" ng-controller="mycontrol">
    <form name="PersonalDetails">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title yellowtitle">
                            <h5>Feedback / Testimonials</h5>
                            <div class="ibox-tools"> <a class="collapse-link"> <i class="fa fa-chevron-up"></i> </a>  </div>
                        </div>
                        <div class="ibox-content">
                            <div class="col-md-4 pad0">

                                <div class="form-group">
                                    <select id="FeedbackSubjectID" ng-model="FeedbackSubjectID" ng-change="selectedItemChanged(FeedbackSubjectID)" class="input-control"
                                            ng-options="o.FeedbackSubjectID as o.Subject for o in getFeedbackSubject">
                                        <option value=""> Feedback Subject</option>
                                    </select>
                                    @*<input type="text" class="input-control" placeholder="Subject" ng-model="txtSubject">*@
                                </div>
                                <div class="form-group">
                                    <textarea name="" cols="5" rows="3" class="input-control" placeholder="Comments" ng-model="txtComments"></textarea>
                                </div>
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <span class="btn bt-choosefile btn-file">
                                        <span class="fileinput-new">Choose file</span> <span class="fileinput-exists">Change</span>
                                        <input type="file" name="..." id="img" ng-model="image" title="Format: JPEG, Size: Min 10KB - Max 300KB, Min: 350px(w) - 350px(H), Max: 1000px(w) - 1000px(H)">
                                    </span> <span class="fileinput-filename"></span> <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">&times;</a>
                                </div>
                                <hr>
                                <div class="col-md-12 pad0">
                                    <button class="btn btn-sm btn-primary" type="submit" ng-click="SubmitFeedback()">Submit</button>
                                </div>
                                <div style="clear:both;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="ibox ">
                        <div class="ibox-title redtitle">
                            <h5>List Of Feedback</h5>
                            <div class="ibox-tools"> <a class="collapse-link"> <i class="fa fa-chevron-up"></i> </a>  </div>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <div class="search-d">
                                    <div class="input-group">
                                        <input type="text" class="searchi">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary btn-xs" type="button">
                                                Submit
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7 pad0">
                                <div class="table-responsive">
                                    <table id="example1" class="table table-striped table-bordered dataTable no-footer">
                                        <thead>
                                            <tr>
                                                <th width="72">Id</th>
                                                @*<th width="196">Image</th>*@
                                                <th width="205">Subject</th>
                                                <th width="251">Created on</th>
                                                <th width="552">Feedback</th>
                                                <th width="552">View File</th>
                                            </tr>
                                        </thead>
                                        <tbody id="GetAllFeedback"></tbody>
                                        <tfoot>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- FeedbackImagePopup -->
        <div class="modal fade" id="FeedbackImagePopup" role="dialog">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">FeedBack Image</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <img id="Feedbackimg" src="" class="img-fluid">
                    </div>
                    <div class="footer">
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
<script src="https://cdn.jsdelivr.net/jquery/1.12.4/jquery.min.js"></script>
<script src="http://ajax.microsoft.com/ajax/jquery/jquery-1.10.2.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.2/angular.min.js"></script>
<script>
    var app = angular.module('app', []);
    app.controller('mycontrol', function ($scope, $http, $location)
    {
        GetData();
        getFeedbackSubjectData();
        function getFeedbackSubjectData() {
            $.ajax({
                url: '@Url.Action("GetFeedbackSubjectList", "Trader")',
                type: "GET",
                Response: ContentType = 'application/json',
                data: {},
                success: function (data) {
                    $scope.getFeedbackSubject = data.FeedbackSubjectList;
                    $scope.$apply();
                },
                error: function (data, textStatus, xhr) {
                    var result = JSON.stringify(data);
                }

            });
        }
        function GetData() {
            $.ajax({
                url: '@Url.Action("GetAllFeedback", "Trader")',
                type: "GET",
                Response: ContentType = 'application/json',
                data: {},
                success: function (data) {
                    var path = "~/Content/CSS/img/";
                    var str = JSON.parse(data);
                    var htmlStr = "";
                    for (var i = 0; i < str.length; i++) {
                      //  var image = Encoding.ASCII.GetString((byte[0]).str[i].FeedbackFile);
                        htmlStr += '<tr id="riskRow">';
                        htmlStr += '<td id="row">' + str[i].FeedbackID + '</td>';
                        htmlStr += '<td>' + str[i].FeedbackSubject + '</td>';
                        htmlStr += '<td>' + str[i].CreateDate + '</td>';
                        htmlStr += '<td>' + str[i].FeedbackComment + '</td>';
                        htmlStr += ' <td><button type="button" onclick="ViewImage(' + '' + str[i].FeedbackID + '' + ')"> <i class="fa fa-eye" aria-hidden="true" title="View"></i></button></td>';
                       // htmlStr += '<td> <img alt="image" class="rounded-circle" src="" width="30" height="30">' + Str[i].FeedbackFile + '</td>'
                        htmlStr += '</tr>';
                    }
                    $("#GetAllFeedback").html(htmlStr)
                }
            });

        }
        $scope.SubmitFeedback = function () {
            var formdata;
            if (window.FormData) {
                formdata = new FormData();
            }
            var Comments = $scope.txtComments;
            var Subject = $scope.FeedbackSubjectID;
          //  var Subject = $scope.txtSubject;
            var file = document.getElementById("img").files[0];
            formdata.append("Image",file);
            formdata.append("Comments", Comments);
            formdata.append("Subject", Subject);
            $.ajax({
                url:'@Url.Action("AddFeedback", "Trader")',
                type: "POST",
                data: formdata,
                dataType: 'json',
                contentType: false,
                processData: false,
                success:function () {
                    alert("Insert  data successfully");
                    location.reload();
                }
            });
        }

    });
    function ViewImage(feedback)
    {
        $.ajax({
            url: '@Url.Action("GetImageById", "Trader")',
            type: "GET",
            Response: ContentType = 'application/json',
            data: { FeedbackID: feedback },
            success: function (data) {
                var path = "../Content/CSS/img/";
                $('#Feedbackimg').attr("src", path + data.FeedBackImage);
                $('#FeedbackImagePopup').modal();
            }

        });
    }

</script>

SignalATM.Web/Views/Trader/IntraTransfers.cshtml
@{
    ViewBag.Title = "IntraTransfers";
    Layout = "~/Views/Shared/tr_master_page.cshtml";
}
<section class="content" ng-app="app" ng-controller="mycontrol">
    <form name="createSignal">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-12 pad0">
                        <div class="ibox">
                            <div class="ibox-title yellowtitle">
                                <h5>Intra Transfer - Wallet </h5>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                    <div class="search-d">
                                        <div class="input-group">
                                            <input type="text" class="searchi">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary btn-xs" type="button">
                                                    Submit
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-10 pad0">
                                    <div class="table-responsive">
                                        <table width="100%" class="table table-striped table-bordered" id="example1">

                                            <thead>
                                                <tr>
                                                    <th width="64">ID</th>
                                                    <th width="68">Voucher</th>
                                                    <th width="152">Date </th>
                                                    <th width="77">Amount</th>

                                                    <th width="162" title="Past">Closing Amount</th>
                                                    <th width="73" title="Past">Type</th>
                                                    <th width="114" title="Past">Transaction</th>
                                                    <th width="256" title="Past">Status</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @*<tr>
                                                        <td>01</td>
                                                        <td><a href="tr-invoice.pdf" target="_blank">WT01</a></td>
                                                        <td>9:30am 15-Nov-19</td>
                                                        <td>50</td>
                                                        <td>20</td>
                                                        <td>Credit</td>
                                                        <td>Wallet Transfer</td>
                                                        <td>Success</td>
                                                    </tr>*@
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </form>
</section>
<script src="http://ajax.microsoft.com/ajax/jquery/jquery-1.10.2.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.2/angular.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery/1.12.4/jquery.min.js"></script>
<script>
    var app = angular.module('app', []);
    app.controller('mycontrol', function ($scope, $http, $location) {
        GetData();
        function GetData() {
            $.ajax({
                url: '@Url.Action("GetIntraTransferDetails", "Trader")',
                type: "GET",
                Response: ContentType = 'application/json',
                data: {},
                success: function (data) {
                    var str = JSON.parse(data);
                    var htmlStr = "";
                    for (var i = 0; i < str.length; i++) {
                        htmlStr += '<tr id="riskRow">';
                        htmlStr += '<td id="row">' + parseInt(i + 1) + '</td>';
                        htmlStr += '<td>' + str[i].PaymentID + '</td>';
                        htmlStr += '<td>' + str[i].EntryDate + '</td>';
                        htmlStr += '<td>' + str[i].TransferredAmount + '</td>';
                        htmlStr += '<td>' + str[i].ReferrerClosingBalance + '</td>';
                        htmlStr += '<td>' + str[i].TransactionDetails + '</td>';
                        //htmlStr += '<td>' + str[i].TransactionDetails + '</td>';
                        // htmlStr += '<td>' + str[i].Comments + '</td>';
                        //htmlStr += '<td>' + str[i].Comments + '</td>';// <div class="more"> <p class="m-0">  </p> </div>
                        //htmlStr += '<td>' + str[i].RequestCompletedOn + '</td>';
                        //htmlStr += ' <td><button type="button"  onclick="Edit(' + '' + str[i].RiskID + '' + ',' + '\'' + str[i].RiskName + '\'' + ',' + '\'' + str[i].Status + '\'' + ',' + '\'' + str[i].EntryDate + '\'' + ')"> <i class="fa fa-edit" aria-hidden="true" title="Edit"></i></button></td>';
                        //htmlStr += ' <td><a href="admin-as-signal-type.html#details"><i class="fa fa-eye" aria-hidden="true" title="View"></i></a></td>';
                        //htmlStr += ' <td><button type="button" class="btn btn-danger btn-xs" onclick="Delete(' + str[i].RiskID + ')"> <i class="fa fa-remove"></i>&nbsp;Remove</button></td>';
                        htmlStr += '</tr>';
                    }
                    $("#InteraTransferDetails").html(htmlStr)
                }
            });
        }
    });
</script>

SignalATM.Web/Views/Trader/SiteMap.cshtml
@{
    ViewBag.Title = "SiteMap";
    Layout = "~/Views/Shared/tr_master_page.cshtml";
}

<h2>SiteMap</h2>

SignalATM.Web/Views/Trader/SuccessPayment.cshtml
@{
    ViewBag.Title = "SuccessPayment";
    Layout = "~/Views/Shared/tr_master_page.cshtml";
}


<h2>Your payment has been processed successfully</h2>
<div class="row">
    <div class="col-md-6">
        <a href="/Trader/Workspace">
            <div class="widget style1 btn-warning" style="padding:5px 0;">
                <div class="row">
                    <div class="col-5 pad0">
                        <i class="fa fa-user-circle" style="font-size:20px; float:right; margin-right:10px; margin-top:2px;"></i>
                    </div>
                    <div class="col-7 text-left pad0" style="margin-top:3px;">
                        <span style="font-size:13px;"> Workspace</span>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-6">
        <a href="/Trader/SubscriptionPlan">
            <div class="widget style1 btn-success" style="padding:5px 0;">
                <div class="row">
                    <div class="col-5 pad0">
                        <i class="fa fa-file" style="font-size:18px; float:right; margin-top:3px; margin-right:10px;"></i>
                    </div>
                    <div class="col-7 text-left pad0" style="margin-top:3px;">
                        <span style="font-size:13px;"> Subscription Plan </span>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>